@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9DbGllbnQiLCJzdWIiOiJ0ZXN0dXNlckNsaWVudEBiYXIuY29tIiwiaWF0IjoxNzUxNTMwMTcwLCJleHAiOjE3NTE1MzM3NzB9.wNKwx39P7ofYcjJ6mE7TYam_YOdDc1eJo2FAb08Cnos





######################################################################## CATEGORIES





GET http://localhost:8000/api/categories
Authorization: Bearer {{token}}

### Get Category by ID
GET http://localhost:8000/api/categories/1
Authorization: Bearer {{token}}

### Create a new Category
POST http://localhost:8000/api/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCategorie": "Mocktails"
}

### Update a Category
PUT http://localhost:8000/api/categories/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCategorie": "Cocktails sans alcool"
}

### Delete a Category
DELETE http://localhost:8000/api/categories/5
Authorization: Bearer {{token}}





######################################################################## COCKTAILS





GET http://localhost:8000/api/cocktails
Authorization: Bearer {{token}}

### Get Cocktail by ID (structuré)
GET http://localhost:8000/api/cocktails/1
Authorization: Bearer {{token}}

### Create a new Cocktail
POST http://localhost:8000/api/cocktails
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCocktail": "Virgin Mojito",
  "descriptionCocktail": "Sans alcool",
  "categorie": { "idCategorie": 1 },
  "createur": { "idUtilisateur": 1 }
}

### Update a Cocktail
PUT http://localhost:8000/api/cocktails/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCocktail": "Virgin Mojito revisité",
  "descriptionCocktail": "Sans alcool, menthe fraîche",
  "categorie": { "idCategorie": 1 },
  "createur": { "idUtilisateur": 1 }
}

### Delete a Cocktail
DELETE http://localhost:8000/api/cocktails/5
Authorization: Bearer {{token}}





######################################################################## COMMANDES





GET http://localhost:8000/api/commandes
Authorization: Bearer {{token}}

### Get Commande by ID
GET http://localhost:8000/api/commandes/1
Authorization: Bearer {{token}}

### Create a new Commande
POST http://localhost:8000/api/commandes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "utilisateur": { "idUtilisateur": 1 }
}

### Update a Commande
PUT http://localhost:8000/api/commandes/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "statutCommande": "Terminée"
}

### Delete a Commande
DELETE http://localhost:8000/api/commandes/1
Authorization: Bearer {{token}}





######################################################################## TAILLES





GET http://localhost:8000/api/tailles
Authorization: Bearer {{token}}

### Get Taille by ID
GET http://localhost:8000/api/tailles/1
Authorization: Bearer {{token}}





######################################################################## UTILISATEURS

GET http://localhost:8000/api/utilisateurs
Authorization: Bearer {{token}}

### Get Utilisateur by ID
GET http://localhost:8000/api/utilisateurs/1
Authorization: Bearer {{token}}

### Create a new Utilisateur
POST http://localhost:8000/api/utilisateurs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "emailUtilisateur": "testuser@bar.com",
  "motDePasse": "password123",
  "roleUtilisateur": "Client"
}

### Delete a Utilisateur
DELETE http://localhost:8000/api/utilisateurs/4
Authorization: Bearer {{token}}





######################################################################## INGREDIENTS





GET http://localhost:8000/api/ingredients
Authorization: Bearer {{token}}

### Get Ingredient by ID
GET http://localhost:8000/api/ingredients/1
Authorization: Bearer {{token}}

### Create a new Ingredient
POST http://localhost:8000/api/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomIngredient": "Menthe"
}

### Update an Ingredient
PUT http://localhost:8000/api/ingredients/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomIngredient": "Menthe fraîche"
}

### Delete an Ingredient
DELETE http://localhost:8000/api/ingredients/5
Authorization: Bearer {{token}}





######################################################################## AUTH





### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "emailUtilisateur": "testuserClient@bar.com",
  "motDePasse": "password123",
  "roleUtilisateur": "Client"
}

### AUTH - Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "emailUtilisateur": "testuserClient@bar.com",
  "motDePasse": "password123"
}

### AUTH - Me
GET http://localhost:8000/auth/me
Authorization: Bearer {{token}}