@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9DbGllbnQiLCJzdWIiOiJ0ZXN0dXNlckNsaWVudEBiYXIuY29tIiwiaWF0IjoxNzUxNDY2NDE5LCJleHAiOjE3NTE0NzAwMTl9.VZait5NNShv5Ymjm3Fo14oHXWUYRqvahb33uGqxTZrs





######################################################################## CATEGORIES





GET http://localhost:8000/api/categories
Authorization: Bearer {{token}}

### Get Category by ID
GET http://localhost:8000/api/categories/1
Authorization: Bearer {{token}}

### Create a new Category
POST http://localhost:8000/api/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCategorie": "Mocktails"
}

### Update a Category
PUT http://localhost:8000/api/categories/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCategorie": "Cocktails sans alcool"
}

### Delete a Category
DELETE http://localhost:8000/api/categories/5
Authorization: Bearer {{token}}





######################################################################## COCKTAILS





GET http://localhost:8000/api/cocktails
Authorization: Bearer {{token}}

### Get Cocktail by ID (détaillé)
GET http://localhost:8000/api/cocktails/1
Authorization: Bearer {{token}}

### Create a new Cocktail
POST http://localhost:8000/api/cocktails
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCocktail": "Virgin Mojito",
  "descriptionCocktail": "Sans alcool",
  "categorie": { "idCategorie": 1 },
  "createur": { "idUtilisateur": 1 }
}

### Update a Cocktail
PUT http://localhost:8000/api/cocktails/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomCocktail": "Virgin Mojito revisité",
  "descriptionCocktail": "Sans alcool, menthe fraîche",
  "categorie": { "idCategorie": 1 },
  "createur": { "idUtilisateur": 1 }
}

### Delete a Cocktail
DELETE http://localhost:8000/api/cocktails/5
Authorization: Bearer {{token}}





######################################################################## COCKTAIL-INGREDIENTS





GET http://localhost:8000/api/cocktail-ingredients
Authorization: Bearer {{token}}

### Get Cocktail-Ingredient by ID
GET http://localhost:8000/api/cocktail-ingredients/1/2
Authorization: Bearer {{token}}

### Get Cocktail-Ingredient by Cocktail ID
GET http://localhost:8000/api/cocktail-ingredients/cocktail/1
Authorization: Bearer {{token}}

### Create a new Cocktail-Ingredient
POST http://localhost:8000/api/cocktail-ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cocktail": { "idCocktail": 1 },
  "ingredient": { "idIngredient": 2 },
  "quantite": 5,
  "unite": "cl"
}

### Update a Cocktail-Ingredient
PUT http://localhost:8000/api/cocktail-ingredients/1/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantite": 6,
  "unite": "cl"
}

### Delete a Cocktail-Ingredient
DELETE http://localhost:8000/api/cocktail-ingredients/1/2
Authorization: Bearer {{token}}





######################################################################## COCKTAIL-TAILLE-PRIX





GET http://localhost:8000/api/cocktail-taille-prix
Authorization: Bearer {{token}}

### Get Cocktail-Taille-Prix by ID
GET http://localhost:8000/api/cocktail-taille-prix/1/2
Authorization: Bearer {{token}}

### Create a new Cocktail-Taille-Prix
POST http://localhost:8000/api/cocktail-taille-prix
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cocktail": { "idCocktail": 1 },
  "taille": { "idTaille": 1 },
  "prix": 7.5
}

### Update a Cocktail-Taille-Prix
PUT http://localhost:8000/api/cocktail-taille-prix/1/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "prix": 8.0
}

### Delete a Cocktail-Taille-Prix
DELETE http://localhost:8000/api/cocktail-taille-prix/1/2





######################################################################## COMMANDES





GET http://localhost:8000/api/commandes
Authorization: Bearer {{token}}

### Get Commande by ID
GET http://localhost:8000/api/commandes/1
Authorization: Bearer {{token}}

### Create a new Commande
POST http://localhost:8000/api/commandes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "utilisateur": { "idUtilisateur": 22 }
}

### Update a Commande
PUT http://localhost:8000/api/commandes/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "statutCommande": "Terminée"
}

### Delete a Commande
DELETE http://localhost:8000/api/commandes/1
Authorization: Bearer {{token}}





######################################################################## TAILLES





GET http://localhost:8000/api/tailles
Authorization: Bearer {{token}}

### Get Taille by ID
GET http://localhost:8000/api/tailles/1
Authorization: Bearer {{token}}





######################################################################## UTILISATEURS

GET http://localhost:8000/utilisateurs
Authorization: Bearer {{token}}

### Get Utilisateur by ID
GET http://localhost:8000/utilisateurs/1
Authorization: Bearer {{token}}

### Create a new Utilisateur
POST http://localhost:8000/utilisateurs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "emailUtilisateur": "testuser@bar.com",
  "motDePasse": "password123",
  "roleUtilisateur": "Client"
}

### Delete a Utilisateur
DELETE http://localhost:8000/utilisateurs/4
Authorization: Bearer {{token}}





######################################################################## INGREDIENTS





GET http://localhost:8000/api/ingredients
Authorization: Bearer {{token}}

### Get Ingredient by ID
GET http://localhost:8000/api/ingredients/1
Authorization: Bearer {{token}}

### Create a new Ingredient
POST http://localhost:8000/api/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomIngredient": "Menthe"
}

### Update a Ingredient
PUT http://localhost:8000/api/ingredients/17
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomIngredient": "Citron"
}

### Delete a Ingredient
DELETE http://localhost:8000/api/ingredients/17





######################################################################## LIGNE-COMMANDES





GET http://localhost:8000/api/ligne-commandes
Authorization: Bearer {{token}}

### Get LigneCommande by ID
GET http://localhost:8000/api/ligne-commandes/1
Authorization: Bearer {{token}}

### Create a new LigneCommande
POST http://localhost:8000/api/ligne-commandes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "commande": { "idCommande": 1 },
  "cocktail": { "idCocktail": 1 },
  "taille": { "idTaille": 1 },
  "quantite": 2,
  "statutCocktailPreparation": "Commandée"
}

### Update a LigneCommande
PUT http://localhost:8000/api/ligne-commandes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantite": 3
}

### Delete a LigneCommande
DELETE http://localhost:8000/api/ligne-commandes/1





######################################################################## AUTH





### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "emailUtilisateur": "testuserClient@bar.com",
  "motDePasse": "password123",
  "roleUtilisateur": "Client"
}

### AUTH - Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "emailUtilisateur": "testuserClient@bar.com",
  "motDePasse": "password123"
}

### AUTH - Me
GET http://localhost:8000/auth/me
Authorization: Bearer {{token}}